//! Regression guard for serve-time MCP tool-catalog attestation
//! (arXiv 2604.20994), wired into the hardened boot path in v0.5.20.
//!
//! Before this, `mnemo mcp-server` loaded the manifest's `[tool_catalog_pin]`,
//! logged "serve-time attestation is NOT enforced in this build", and served
//! anyway — the pin was parsed and thrown away (same claimed-but-not-wired class
//! as the role_filter bug fixed 2026-07-28 and the capability lease removed
//! 2026-07-29). A LIBRARY test over `PinnedAttestor` (which already existed and
//! passed) would not have caught it, because the library was never broken — only
//! the binary dropped the verdict. So this drives the **real `mnemo` binary**
//! over stdio.
//!
//! Cases:
//!   * correct pin (generated by `--print-catalog-pin`) → server starts, tools/list works;
//!   * one `schema_sha256` byte flipped (mutated) → binary exits non-zero, never serves;
//!   * an extra pin row absent from the binary (removed-only drift) → refused without
//!     `allow_removed_drift`, accepted with it.
//!
//! Verified to FAIL against the pre-fix binary: pre-fix, every case served (the
//! mutated + removed pins were ignored), so `tools/list` succeeded where this
//! test now requires a non-zero exit.

use std::io::{BufRead, BufReader, Write};
use std::process::{Child, Command, Stdio};
use std::sync::mpsc::{Receiver, channel};
use std::time::{Duration, Instant};

use serde_json::{Value, json};

const READ_TIMEOUT: Duration = Duration::from_secs(30);

fn write_keystore(dir: &tempfile::TempDir) -> std::path::PathBuf {
    let path = dir.path().join("keystore.toml");
    std::fs::write(
        &path,
        "key_id = \"test-key\"\n\
         key_hex = \"00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff\"\n",
    )
    .unwrap();
    path
}

/// Write a manifest. `extra` is appended verbatim (e.g. the
/// `tool_catalog_pin_path` + `allow_removed_drift` lines).
fn write_manifest(dir: &tempfile::TempDir, name: &str, extra: &str) -> std::path::PathBuf {
    let keystore = write_keystore(dir);
    let body = format!(
        "keystore_path = \"{}\"\n\
         audit_log_path = \"{}\"\n\
         allowed_tools = [\"mnemo.recall\", \"mnemo.verify\"]\n\
         allowed_agents = []\n\
         allowed_parents = []\n{extra}",
        keystore.display(),
        dir.path().join("audit.jsonl").display(),
    );
    let path = dir.path().join(name);
    std::fs::write(&path, body).unwrap();
    path
}

fn clean_env(cmd: &mut Command, dir: &tempfile::TempDir) {
    cmd.env_clear()
        .env("PATH", std::env::var("PATH").unwrap_or_default())
        .env("HOME", std::env::var("HOME").unwrap_or_default())
        .env("RUST_BACKTRACE", "0")
        .env("MNEMO_DB_PATH", dir.path().join("mnemo.db"));
}

/// Run `mnemo mcp-server --manifest <m> --print-catalog-pin` and return the
/// emitted pin TOML. Exits 0 without serving.
fn generate_pin(dir: &tempfile::TempDir, manifest: &std::path::Path) -> String {
    let mut cmd = Command::new(env!("CARGO_BIN_EXE_mnemo"));
    cmd.arg("mcp-server")
        .arg("--manifest")
        .arg(manifest)
        .arg("--print-catalog-pin")
        .stderr(Stdio::null());
    clean_env(&mut cmd, dir);
    let out = cmd.output().expect("run --print-catalog-pin");
    assert!(
        out.status.success(),
        "--print-catalog-pin must exit 0, got {:?}",
        out.status
    );
    let pin = String::from_utf8(out.stdout).expect("pin is utf8");
    assert!(
        pin.contains("[tool_catalog_pin]") && pin.contains("[[tool_catalog_pin.tools]]"),
        "pin must contain the expected TOML sections:\n{pin}"
    );
    pin
}

fn boot(dir: &tempfile::TempDir, manifest: &std::path::Path) -> Child {
    let mut cmd = Command::new(env!("CARGO_BIN_EXE_mnemo"));
    cmd.arg("mcp-server")
        .arg("--manifest")
        .arg(manifest)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::null());
    clean_env(&mut cmd, dir);
    cmd.spawn().expect("spawn mnemo binary")
}

fn line_reader(child: &mut Child) -> Receiver<String> {
    let stdout = child.stdout.take().expect("child stdout");
    let (tx, rx) = channel::<String>();
    std::thread::spawn(move || {
        for line in BufReader::new(stdout).lines() {
            match line {
                Ok(l) => {
                    if tx.send(l).is_err() {
                        break;
                    }
                }
                Err(_) => break,
            }
        }
    });
    rx
}

fn send(child: &mut Child, frame: &Value) {
    let stdin = child.stdin.as_mut().expect("child stdin");
    writeln!(stdin, "{frame}").expect("write json-rpc frame");
    stdin.flush().expect("flush stdin");
}

fn recv_id(rx: &Receiver<String>, id: i64) -> Value {
    let deadline = Instant::now() + READ_TIMEOUT;
    loop {
        let remaining = deadline.saturating_duration_since(Instant::now());
        assert!(!remaining.is_zero(), "timed out waiting for id={id}");
        let line = rx
            .recv_timeout(remaining)
            .unwrap_or_else(|_| panic!("timed out waiting for id={id}"));
        if let Ok(v) = serde_json::from_str::<Value>(&line)
            && v.get("id").and_then(Value::as_i64) == Some(id)
        {
            return v;
        }
    }
}

/// Initialize + tools/list; returns the tool names.
fn handshake_and_list(child: &mut Child, rx: &Receiver<String>) -> Vec<String> {
    send(
        child,
        &json!({
            "jsonrpc": "2.0", "id": 1, "method": "initialize",
            "params": {"protocolVersion": "2025-06-18", "capabilities": {},
                       "clientInfo": {"name": "attest-test", "version": "0"}}
        }),
    );
    let init = recv_id(rx, 1);
    assert!(init.get("result").is_some(), "initialize failed: {init}");
    send(
        child,
        &json!({"jsonrpc": "2.0", "method": "notifications/initialized"}),
    );
    send(
        child,
        &json!({"jsonrpc": "2.0", "id": 2, "method": "tools/list", "params": {}}),
    );
    let list = recv_id(rx, 2);
    list["result"]["tools"]
        .as_array()
        .expect("tools/list result.tools")
        .iter()
        .map(|t| t["name"].as_str().unwrap_or_default().to_string())
        .collect()
}

/// Close stdin and wait (bounded) for the child to exit; returns its code.
/// Used for the "must refuse" cases: attestation failure returns before
/// `serve(stdio())`, so the process exits promptly on its own. Closing stdin
/// means that even if it (buggily) served, EOF would end it — so a hang here is
/// itself a failure of the guard.
fn wait_exit_code(mut child: Child) -> Option<i32> {
    drop(child.stdin.take());
    let deadline = Instant::now() + Duration::from_secs(30);
    loop {
        match child.try_wait().expect("try_wait") {
            Some(status) => return status.code(),
            None if Instant::now() >= deadline => {
                let _ = child.kill();
                panic!("binary did not exit within 30s — it served despite a bad pin");
            }
            None => std::thread::sleep(Duration::from_millis(50)),
        }
    }
}

fn shutdown(mut child: Child) {
    drop(child.stdin.take());
    let _ = child.kill();
    let _ = child.wait();
}

#[test]
fn correct_pin_starts_and_lists_tools() {
    let dir = tempfile::tempdir().unwrap();
    // A manifest with no pin, to generate the pin for this exact binary.
    let gen_manifest = write_manifest(&dir, "gen.toml", "");
    let pin = generate_pin(&dir, &gen_manifest);
    let pin_path = dir.path().join("pin.toml");
    std::fs::write(&pin_path, &pin).unwrap();

    let manifest = write_manifest(
        &dir,
        "serve.toml",
        &format!("tool_catalog_pin_path = \"{}\"\n", pin_path.display()),
    );
    let mut child = boot(&dir, &manifest);
    let rx = line_reader(&mut child);
    let tools = handshake_and_list(&mut child, &rx);
    assert!(
        tools.iter().any(|t| t == "mnemo.recall"),
        "correct pin: server must start and advertise its tools, got {tools:?}"
    );
    shutdown(child);
}

#[test]
fn mutated_pin_refuses_to_serve() {
    let dir = tempfile::tempdir().unwrap();
    let gen_manifest = write_manifest(&dir, "gen.toml", "");
    let pin = generate_pin(&dir, &gen_manifest);

    // Flip one hex char of the FIRST schema_sha256 → a mutated fingerprint.
    let mut mutated = String::new();
    let mut flipped = false;
    for line in pin.lines() {
        if !flipped && line.trim_start().starts_with("schema_sha256 = ") {
            // change the first hex digit inside the quotes
            let idx = line.find('"').unwrap() + 1;
            let orig = line.as_bytes()[idx] as char;
            let repl = if orig == '0' { '1' } else { '0' };
            let mut chars: Vec<char> = line.chars().collect();
            chars[idx] = repl;
            mutated.push_str(&chars.into_iter().collect::<String>());
            flipped = true;
        } else {
            mutated.push_str(line);
        }
        mutated.push('\n');
    }
    assert!(flipped, "expected at least one schema_sha256 row to mutate");
    let pin_path = dir.path().join("mutated.toml");
    std::fs::write(&pin_path, &mutated).unwrap();

    let manifest = write_manifest(
        &dir,
        "serve.toml",
        &format!("tool_catalog_pin_path = \"{}\"\n", pin_path.display()),
    );
    let child = boot(&dir, &manifest);
    let code = wait_exit_code(child);
    assert_ne!(
        code,
        Some(0),
        "mutated pin: binary must exit NON-ZERO and never serve (got exit {code:?})"
    );
}

#[test]
fn removed_only_drift_refused_without_flag_accepted_with_it() {
    let dir = tempfile::tempdir().unwrap();
    let gen_manifest = write_manifest(&dir, "gen.toml", "");
    let pin = generate_pin(&dir, &gen_manifest);

    // Add a `secret_exfil` row the binary does NOT advertise → from the
    // advertised catalog's view it is REMOVED (present in pin, absent in binary).
    let secret_row = "\n[[tool_catalog_pin.tools]]\nname = \"secret_exfil\"\n\
         schema_sha256 = \"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\"\n";
    let pin_with_extra = format!("{pin}{secret_row}");
    let pin_path = dir.path().join("removed.toml");
    std::fs::write(&pin_path, &pin_with_extra).unwrap();

    // Without allow_removed_drift → refuse.
    let m_refuse = write_manifest(
        &dir,
        "refuse.toml",
        &format!("tool_catalog_pin_path = \"{}\"\n", pin_path.display()),
    );
    let code = wait_exit_code(boot(&dir, &m_refuse));
    assert_ne!(
        code,
        Some(0),
        "removed-only drift WITHOUT allow_removed_drift must refuse (got exit {code:?})"
    );

    // With allow_removed_drift = true → serve.
    let m_allow = write_manifest(
        &dir,
        "allow.toml",
        &format!(
            "tool_catalog_pin_path = \"{}\"\nallow_removed_drift = true\n",
            pin_path.display()
        ),
    );
    let mut child = boot(&dir, &m_allow);
    let rx = line_reader(&mut child);
    let tools = handshake_and_list(&mut child, &rx);
    assert!(
        tools.iter().any(|t| t == "mnemo.recall"),
        "removed-only drift WITH allow_removed_drift must serve, got {tools:?}"
    );
    shutdown(child);
}
